- id: doi:10.1101/2022.12.13.520194
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2022.12.13.520194v1

- id: doi:10.1159/000525019

- id: doi:10.1126/science.abd9704
  image: images/science_summary.svg

- id: doi:10.1093/gigascience/giy008
  image: images/BF_pic.png

- id: doi.org:10.1016/j.neuron.2014.07.013
  image: images/neuron_dhs.svg